### ISSUE TITLE
Upgrade acorn to version 5.7.4 or later

### ISSUE THREAD

**Issue by njm222** [njm222/Spotify_Visualizer#3]
Remediation
Upgrade acorn to version 5.7.4 or later. For example:

"dependencies": {
  "acorn": ">=5.7.4"
}
or…
"devDependencies": {
  "acorn": ">=5.7.4"
}

**Comment by LevinWeinstein** [comment]
Can't dependabot do this in one click?

**Comment by LevinWeinstein** [comment]
it gave me a memo on my repos that it wanted to do this and I just clicked 'ok'

**Comment by njm222** [comment]
Yeah you are correct, I just did it, thanks!
